export enum UserErrorCode {
  ACCOUNT_ALREADY_EXISTED = "account_already_existed",
  INVALID_CREDENTIAL = "invalid_credential",
  USER_NOT_FOUND = "user_not_found",
  INVALID_ID = "invalid_id",
  INVALID_OWNER = "invalid_owner",
  DISPLAY_NAME_ALREADY_IN_USE = "display_name_already_in_use",
  INVALID_TOKEN = "invalid_token",
  POST_NOT_FOUND = "post_not_found",
  POST_NOT_SAVED = "post_not_saved",
  POST_SAVED_ALREADY = "post_saved_already",
  COMMENT_NOT_FOUND = "comment_not_found" ,
  FOOD_NOT_FOUND = "food_not_found",
  ALBUM_NOT_FOUND = "album_not_found",
  CONVERSATION_NOT_FOUND = "conversation_not_found",
  MESSAGE_NOT_FOUND = "message_not_found",
  VOTE_NOT_FOUND = "vote_not_found",
  UNIT_ALREADY_EXISTED= "unit_already_existed",
  INGREDIENT_ALREADY_EXISTED= "ingredient_already_existed",
  TOPIC_ALREADY_EXISTED= "topic_already_existed",
  FOOD_ALREADY_CONFIRMED = "food_already_confirmed",
  FOOD_ALREADY_SAVED = "food_already_saved",
  OLD_PASSWORD_NOT_CORRECT = "old_password_not_correct",
  FOOD_NOT_SAVE = "food_not_save",
  ROLE_NOT_FOUND = "role_not_found"
}
