version: '3'
services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - pg-tastify:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: 
      - .postgres.env
volumes:
  pg-tastify:
